= Quarkus Azure Service Bus Extension

include::./includes/attributes.adoc[]

include::./includes/support.adoc[]

https://azure.microsoft.com/products/service-bus[Azure Service Bus] is a fully managed enterprise message broker with message queues and publish-subscribe topics. Service Bus is used to decouple applications and services from each other.

This extension provides the following benefits:

- It resolves native build issues so that applications using the Azure Service Bus with the Azure SDK for Java can be compiled to a native image.
- It injects `com.azure.messaging.servicebus.ServiceBusClientBuilder` instances that can be used to create clients for an Azure Service Bus that send and consume messages.
- The Dev Services launch an Azure Service Bus emulator in dev and test mode and configure the injected builders to use it.

This is a step by step guide on how to use the Quarkus Azure Service Bus extension. If you're looking for a complete code sample, you can find it in the https://github.com/quarkiverse/quarkus-azure-services/tree/main/integration-tests/azure-servicebus[Azure Service Bus sample].

== Installation

Add a dependency on `io.quarkiverse.azureservices:quarkus-azure-servicebus`.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.azureservices</groupId>
    <artifactId>quarkus-azure-servicebus</artifactId>
    <version>{project-version}</version>
</dependency>
----

== How to Use It

Once you have added the extension to your project, follow the next steps, so you can inject `com.azure.messaging.servicebus.ServiceBusClientBuilder` object in your application to create clients for producing and consuming messages from Azure Service Bus.

=== Setup your Azure Environment

include::includes/azure-setup-environment.adoc[]

Create an Azure resource group with the az group create command.
A resource group is a logical container into which Azure resources are deployed and managed.

[source,shell]
----
az group create \
    --name rg-quarkus-azure-servicebus \
    --location westus
----

Create an Azure Service Bus namespace and a queue with the following commands:

[source,shell]
----
az servicebus namespace create \
    --name sbnamespace20250604 \
    --resource-group rg-quarkus-azure-servicebus

az servicebus queue create \
    --name test-queue \
    --namespace-name sbnamespace20250604 \
    --resource-group rg-quarkus-azure-servicebus
----

If you log into the http://portal.azure.com/[Azure portal], you can see the resource group and the Azure Service Bus namespace you created.

=== Configure the Azure Service Bus Client Builder

As you can see below in the _Extension Configuration Reference_ section, either the property `quarkus.azure.servicebus.namespace` or the property `quarkus.azure.servicebus.connection-string` is required if the extension is enabled.

You have two options to authenticate to Azure Service Bus, either with Microsoft Entra ID or connection string. The following sections describe how to authenticate with both options. For optimal security, it is recommended to use Microsoft Entra ID for authentication.

==== Authenticating to Azure Service Bus with Microsoft Entra ID

You can authenticate to Azure Service Bus with Microsoft Entra ID. Run the following commands to assign the `Azure Service Bus Data Owner` role to the signed-in user as a Microsoft Entra identity.

[source,shell]
----
SERVICEBUS_RESOURCE_ID=$(az servicebus namespace show \
    --resource-group rg-quarkus-azure-servicebus \
    --name sbnamespace20250604 \
    --query 'id' \
    --output tsv)
OBJECT_ID=$(az ad signed-in-user show --query id -o tsv)

az role assignment create \
    --role "Azure Service Bus Data Owner" \
    --assignee ${OBJECT_ID} \
    --scope $SERVICEBUS_RESOURCE_ID
----

Run the following commands to export the namespace of the Azure Service Bus as an environment variable.

[source,shell]
----
export QUARKUS_AZURE_SERVICEBUS_NAMESPACE=sbnamespace20250604
----

The value of environment variable `QUARKUS_AZURE_SERVICEBUS_NAMESPACE` will be read by Quarkus as the value of config property `quarkus.azure.servicebus.namespace` of `azure-servicebus` extension in order to set up the connection to the Azure Service Bus.

==== Authenticating to Azure Service Bus with connection string

You can also authenticate to Azure Service Bus with connection string. Run the following commands to export the connection string of the Azure Service Bus as an environment variable.

[source,shell]
----
export QUARKUS_AZURE_SERVICEBUS_CONNECTION_STRING=$(az servicebus namespace authorization-rule keys list \
    --resource-group rg-quarkus-azure-servicebus \
    --namespace-name sbnamespace20250604 \
    --name RootManageSharedAccessKey \
    --query primaryConnectionString -o tsv)
----

The value of environment variable `QUARKUS_AZURE_SERVICEBUS_CONNECTION_STRING` will be read by Quarkus as the value of config property `quarkus.azure.servicebus.connection-string` of `azure-servicebus` extension in order to set up the connection to the Azure Service Bus.

=== Inject the Azure Service Bus Client Builder

Now that your Azure environment is ready and you have configured the extension, you can `@Inject` the `com.azure.messaging.servicebus.ServiceBusClientBuilder` object in your application, so you can create clients to interact with Azure Servie Bus.
For complete API see the https://javadoc.io/doc/com.azure/azure-messaging-servicebus/latest/index.html[Azure SDK for Java Reference Documentation].

==== Use the ServiceBusClientBuilder to create clients

[source,java]
----
@ApplicationScoped
public class ServiceBusManager {

    private static final Logger LOG = Logger.getLogger(ServiceBusManager.class);

    @ConfigProperty(name = "quarkus.azure.servicebus.queue-name", defaultValue = "test-queue")
    private String queueName;

    @Inject
    private ServiceBusClientBuilder clientBuilder;

    private ServiceBusSenderClient senderClient;
    private ServiceBusProcessorClient processorClient;

    // Thread-safe list to store received messages for testing
    private final List<String> receivedMessages = new CopyOnWriteArrayList<>();

    @PostConstruct
    void initialize() {
        LOG.info("Initializing Azure Service Bus clients");

        // Initialize sender client
        senderClient = clientBuilder
                .sender()
                .queueName(queueName)
                .buildClient();

        // Initialize processor client with message handler
        processorClient = clientBuilder
                .processor()
                .queueName(queueName)
                .receiveMode(ServiceBusReceiveMode.RECEIVE_AND_DELETE)
                .processMessage(context -> {
                    String body = context.getMessage().getBody().toString();
                    receivedMessages.add(body);
                    LOG.infof("Received message: %s", body);
                })
                .processError(context -> {
                    LOG.errorf("Error occurred: %s", context.getException());
                })
                .disableAutoComplete()
                .buildProcessorClient();

        // Start processing messages
        processorClient.start();

        LOG.info("Azure Service Bus clients initialized successfully");
    }

    @PreDestroy
    void cleanup() {
        LOG.info("Cleaning up Azure Service Bus clients");

        if (processorClient != null) {
            processorClient.close();
        }

        if (senderClient != null) {
            senderClient.close();
        }

        LOG.info("Azure Service Bus clients cleaned up successfully");
    }

    public void sendMessage(String messageBody) {
        LOG.infof("Sending message: %s", messageBody);

        ServiceBusMessage message = new ServiceBusMessage(messageBody);
        senderClient.sendMessage(message);

        LOG.info("Message sent successfully");
    }

    public List<String> getReceivedMessages() {
        return List.copyOf(receivedMessages);
    }
}
----

==== Send and retrieve messages in a REST resource

[source,java]
----
@Path("/quarkus-azure-servicebus")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class ServiceBusResource {

    private static final Logger LOG = Logger.getLogger(ServiceBusResource.class);

    @Inject
    ServiceBusManager serviceBusManager;

    @POST
    @Path("/messages")
    public Response sendMessage(Map<String, String> request) {
        String message = request.get("message");
        LOG.infof("REST request to send message: %s", message);
        serviceBusManager.sendMessage(message);

        return Response.ok(Map.of(
                "status", "success",
                "message", "Message sent successfully")).build();
    }

    @GET
    @Path("/messages")
    public Response getMessages() {
        List<String> messages = serviceBusManager.getReceivedMessages();
        LOG.infof("REST request to get messages, returning %d messages", messages.size());

        return Response.ok(Map.of(
                "status", "success",
                "count", messages.size(),
                "messages", messages)).build();
    }
}
----

To test this sample you can run the following cURL commands after the application is started:

* `curl http://localhost:8080/quarkus-azure-servicebus/messages -X POST -d '{"message": "Hello Azure Service Bus!"}' -H "Content-Type: application/json"`
* `curl http://localhost:8080/quarkus-azure-servicebus/messages`

You should see similar outputs:

```
{"status":"success","message":"Message sent successfully"}
{"messages":["Hello Azure Service Bus!"],"status":"success","count":1}
```

When you're done with the example and no longer need the Azure resources, run the following command to clean up the Azure resources you created before:

[source,shell]
----
az group delete \
    --name rg-quarkus-azure-servicebus \
    --yes --no-wait
----

== Dev Services

The Dev Services of this extension launch an https://learn.microsoft.com/en-us/azure/service-bus-messaging/overview-emulator[Azure Service Bus emulator] in dev and test mode.

The ServiceBusClientBuilder instances produced by this extension will be automatically configured to use the emulator's connection string when running in dev or test mode through the `quarkus.azure.servicebus.connection-string` property.

=== Prerequisites

The Azure Service Bus emulator consists of two containers:

1. The Azure Service Bus emulator container
2. A Microsoft SQL Server database container

To use the Dev Services functionality, you must explicitly accept the license terms for both products:

* Azure Service Bus Emulator EULA: https://github.com/Azure/azure-service-bus-emulator-installer/blob/main/EMULATOR_EULA.txt[View license]
* Microsoft SQL Server EULA: https://go.microsoft.com/fwlink/?linkid=857698[View license]

You can accept both licenses by setting the following configuration:

[source,properties]
----
quarkus.azure.servicebus.devservices.license-accepted=true
----

=== Configure the Azure Service Bus emulator

The emulator is configured via a configuration file in JSON format.
See this link:https://github.com/Azure/azure-service-bus-emulator-installer/blob/main/ServiceBus-Emulator/Config/Config.json[example] for its syntax.

The configuration file is expected at `src/main/azure/servicebus-emulator/config.json`.
If it does not exist, a warning is issued and a fallback configuration
providing a queue "queue" and a topic "topic" with a subscription "subscription" is applied.

=== Disable the Dev Services

The Dev Services will not start under any of these conditions:

- A Service Bus connection is configured via `quarkus.azure.servicebus.namespace` or `quarkus.azure.servicebus.connection-string`
- The Dev Services are explicitly disabled with `quarkus.azure.servicebus.devservices.enabled=false`
- Global Dev Services are disabled with `quarkus.devservices.enabled=false`

== Extension Configuration Reference

include::includes/quarkus-azure-servicebus.adoc[leveloffset=+1, opts=optional]
